### ISSUE TITLE
Crashes on startup with GLXBadDrawable on Mesa drivers

### ISSUE THREAD

**Issue by feilen** [feilen/dolphin#1]
This would appear to be a known issue with how the Oculus Rift SDK calls GetDrawableAttributes, calling them on a naked window rather than a glx-decorated window. Fixing this may solve the couple frames of glitchyness that occurs when the window starts up, but it appear to be an issue in the SDK.

Some users with older Nvidia graphics drivers have reported this issue as well, although it's entirely possible that it's a different issue altogether. If there is a way to ensure that the X window is glX decorated before running ovrhmd_ConfigureRendering() then that would be the most likely place to start.

https://bugs.freedesktop.org/show_bug.cgi?format=multiple&id=54080

**Comment by shinyquagsire23** [comment]
I've been getting these crashes in bspwm, so if it's tied to window decoration I might try it in some other environments to see if it makes a difference.

**Comment by feilen** [comment]
Alright! Give it a shot. I believe with Mesa drivers it's actually a known
issue with undefined behavior being called in the Oculus SDK, but if
there's another unrelated crash it'd be good to know about.

**Comment by feilen** [comment]
I'm pretty certain that the reason that this is happening is because the ovr_ConfigureRendering is called before Dolphin actually completes its first frame. We need to the configuration step until a frame has been given, or fill in our own frame somehow.
